apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: qecon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qecon
  name: qecon
  namespace: qecon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: qecon
      app.kubernetes.io/name: qecon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: qecon
        app.kubernetes.io/name: qecon
    spec:
      containers:
      - image: dllhb/go-demo:v1.1.2
        imagePullPolicy: IfNotPresent
        name: qecon
        envFrom:
        - secretRef:
            name: qecon
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
