apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml


generators:
 - ./kops-secret.yaml

generatorOptions:
  labels:
    deploy.type: kustomize
  disableNameSuffixHash: true
