apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: qecon-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qecon
  name: qecon
  namespace: qecon
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9999
  selector:
    app.kubernetes.io/instance: qecon-demo
    app.kubernetes.io/name: qecon
  sessionAffinity: None
  type: ClusterIP
