apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: argocd-sops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-sops
  name: argocd-sops
  namespace: argocd-sops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9999
  selector:
    app.kubernetes.io/instance: argocd-sops
    app.kubernetes.io/name: argocd-sops
  sessionAffinity: None
  type: ClusterIP
